apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
    - name: pod-secret
      image: ubuntu
      env:
        - name: DB_PW
          valueFrom: #여기서는 valueFrom이지만 envFrom을 통해 전부 가져올 수 있다.
            secretKeyRef:
              name: app-secret # secret의 이름을 적어줘야 알맞은 key를 가져올 수 있다.
              key: DB_PASSWORD