apiVersion: v1
kind: Pod
metadata:
  name: new-sa-pod
spec:
  containers:
    - name: new-sa-pod
      image: ubuntu
  serviceAccountName: mysa # 사용할 service account 이름
  # 쿠버네티스는 자동으로 기본 서비스 계정을 마운트한다. 아래를 false로 하면 그러지 않는다.
  automountServiceAccountToken: false